name: "example"

services:
  one:
    image: nginxdemos/hello:0.4

  two:
    image: nginxdemos/hello:0.4

  tri:
    image: nginxdemos/hello:0.4

  for:
    image: nginxdemos/hello:0.4

networks:
  example-network:
    name: example-network
    driver: bridge
